import React, { useState } from "react";
import Table from "../Table/Table";
import { ChoosenDataContext, ChoosenDataProvider } from "../context/choosenDataFromTable";

const ShowDevices: React.FC = () => {
    const [values, setValues] = useState([""]);
    fetch("http://localhost:3001/query")
        .then(res => res.json())
        .then(data => {
            setValues(
                [
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny",
                    "Typ",
                    "Model",
                    "Producent",
                    "Opis techniczny",
                    "Stan techniczny",
                    "Numer Ewidencyjny"
                  ]
            )
        });
    return(
        <ChoosenDataProvider values={[]}>
            <Table titles={[
                "Typ",
                "Model",
                "Producent",
                "Opis techniczny",
                "Stan techniczny",
                "Numer Ewidencyjny"
              ]} values={values}></Table>
        </ChoosenDataProvider>
    )
}
export default ShowDevices;