import React, { useState } from "react";
import Table from "../Table/Table";

interface IProps {
  query: string;
}
const ShowDevices: React.FC<IProps> = ({ query }) => {
  const [values, setValues] = useState([""]);
  fetch(`http://localhost:3001/query?${query}`)
    .then(res => res.json())
    .then(data => {
      setValues([
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny"
      ]);
    });
  return (
    <Table
      titles={[
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny"
      ]}
      values={values}
    ></Table>
  );
};
export default ShowDevices;
