import React, { useState } from "react";
import Table from "../Table/Table";
import { ChoosenDataProvider } from "../context/choosenDataFromTable";

interface IProps {
  query: string;
}
const ShowDevices: React.FC<IProps> = ({ query }) => {
  const [values, setValues] = useState([""]);
  fetch(`http://localhost:3001/query?${query}`)
    .then(res => res.json())
    .then(data => {
      setValues([
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny",
        "Typ",
        "Model",
        "Producent",
        "Opis techniczny",
        "Stan techniczny",
        "Numer Ewidencyjny"
      ]);
    });
  return (
    <ChoosenDataProvider values={[]}>
      <Table
        titles={[
          "Typ",
          "Model",
          "Producent",
          "Opis techniczny",
          "Stan techniczny",
          "Numer Ewidencyjny"
        ]}
        values={values}
      ></Table>
    </ChoosenDataProvider>
  );
};
export default ShowDevices;
